### ISSUE TITLE
Switch Service Principal?

### ISSUE THREAD

**Issue by wbprice** [serverless/serverless-azure-functions#101]
Hello! I had a problem deploying a Serverless project developed in my personal Azure account to my work's Azure account.

When it was time to switch over, I:
- Removed the project from my personal account with `sls remove`
- Logged out of my personal account with `az logout`
- Set my work account to default in `az`

However, when I used `sls deploy`, the project ended up back in my personal account.

I was able to get around this in the short-term by setting the service principal using environment variables as described [in the docs](https://serverless.com/framework/docs/providers/azure/guide/credentials/).

It looks like `serverless` picks one service principal during the first deploy and then uses it for all future deploys.  It would be really great if there were a way to switch between service principals in the CLI (or better yet, have serverless use whatever service principal is set to default in Azure)

**Comment by katchme88** [comment]
Did you clear the environment variables of your tenant id and subscription?

**Comment by katchme88** [comment]
If you are using linux for deploys, you can set up two user accounts one for your personal use and the other for work deploys. Then you can set the environment variables for each account separately to separate the deployment processes to different accounts.

**Comment by wbprice** [comment]
Yes, that would make sense.

When I deployed my project the first time, I followed the directions [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal) to create a service principal through the interactive login experience.  As far as I know, that didn't create any environment variables to override.

**Comment by katchme88** [comment]
Yes, that's sounds like the problem. When you use interactive login, serverless creates a principal for you and use it for later deployments. Setting up the environment variables is the advanced options that should be used if you have multiple subscriptions/accounts to deploy on. I ran into the same issue and found that separating the deploy accounts is the best option you can get so far.

**Comment by rupakg** [comment]
@wbprice can you check under the `~/.azure` folder if the creds are cached? If so, just delete the creds, but leave the folder as-is. See if it works.

**Comment by fiveisprime** [comment]
Closing this as the referenced issue indicates the plugin isn't being used after all. Open it back up if you still need help with this.
