### ISSUE TITLE
Support for deployment slots

### ISSUE THREAD

**Issue by svaj** [serverless/serverless-azure-functions#108]
It would be great if support for deployment slots was added.  Currently I use serverless to package my application and then deploy to a slot via the zip push REST API https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push.  Ideally serverless could handle creation of deploy slots if needed.

**Comment by tbarlow12** [comment]
@svaj thanks for bringing this up. It is on our roadmap. Closing in favor of #372
