### ISSUE TITLE
Rename build directory

### ISSUE THREAD

**Issue by christopheranderson** [serverless/serverless-azure-functions#11]
I suggest we rename the build directory "functions" to ".azure" or ".azurefunctions".

**Comment by Trane9991** [comment]
PR #83 removed the use of `functions` folder. Now default `.serverless` directory is used to store function package.

**Comment by lostintangent** [comment]
@Trane9991 Good catch! I'll close this for now, since I think aligning with the "standard" Serverless packaging mechanism is what we want, and it didn't exist when this issue was filed.
