### ISSUE TITLE
Login failure if ~/.azure doesn't exist

### ISSUE THREAD

**Issue by ndarilek** [serverless/serverless-azure-functions#110]
Attempted to log in several times, but was told that /home/nolan/.azure/azloginServicePrincipal.json didn't exist. Makes sense, as the plugin hadn't authenticated yet.

To make this work, I had to create the ~/.azure directory. Surprised that wasn't done automatically.

**Comment by gilbert** [comment]
Thank you @ndarilek, I had this problem too but didn't know what to do. Your solution worked perfectly.

**Comment by TomSeldon** [comment]
Thanks, I had the same problem. Login was silently failing after authenticating. Creating an empty `~/.azure` directory (and rerunning `sls deploy`) fixed it.

**Comment by xtrycatchx** [comment]
confirmed, my problem disappears after creating the  ~/.azure directory

**Comment by mikhailshilkov** [comment]
Same issue, had to create `azure` folder in `C:\Users\username`

**Comment by jurby** [comment]
+1

**Comment by supoved** [comment]
+1

**Comment by tomaustin700** [comment]
+1

**Comment by derekshull** [comment]
+1

**Comment by michael-watson** [comment]
+1
Still the same silly issue

**Comment by alexandergottlieb** [comment]
+1

**Comment by DrSandhu** [comment]
+1

**Comment by saadismail** [comment]
+1, just faced this issue.

**Comment by PerpetualWar** [comment]
Same here... should be fixed or better documeted.

**Comment by hrchu** [comment]
+1
