### ISSUE TITLE
When is the next release of the plugin?

### ISSUE THREAD

**Issue by martosoler** [serverless/serverless-azure-functions#111]
Hi,

Sorry if it sounds rude but I was looking at the issue [93](https://github.com/serverless/serverless-azure-functions/issues/93) which is blocking other things at my side and wonder when will the related PR be merged or when a new release will happen.

I can get the artifact from that commit but I would rather use a release version.

Thanks

**Comment by fiveisprime** [comment]
Everything is merged and landed in 0.5.0.
