### ISSUE TITLE
How to set the node version?

### ISSUE THREAD

**Issue by PhilAndrew** [serverless/serverless-azure-functions#113]

**Comment by mapsi** [comment]
I am having this same problem.
I know I can set the runtime version in the *Function app settings* to "beta" and
```
FUNCTIONS_EXTENSION_VERSION = beta 
WEBSITE_NODE_DEFAULT_VERSION = 8.9.4
```
in *Application settings* but with every redeploy these are reset to the default values, ie
```
FUNCTIONS_EXTENSION_VERSION = ~1
WEBSITE_NODE_DEFAULT_VERSION = 6.5.0
```

**Comment by JohnReeson** [comment]
@mapsi if you use `serverless deploy`, it recreates the whole function app every time, so you will see the resetting.

**Comment by derekshull** [comment]
Is there a way to permanently set these so that `serverless deploy` doesn't reset them?  Really need this!

**Comment by abizake** [comment]
@derekshull  Late but if this helps ....
It does not reset it , it uses the default value present in the arm templates.
WorkAround on windows :- 
((Get-Content node_modules\\serverless-azure-functions\\provider\\armTemplates\\azuredeploy.json).replace('6.5.0', '8.11.3') ) | Set-Content -Path .\node_modules\serverless-azure-functions\provider\armTemplates\azuredeploy.json

**Comment by JohnReeson** [comment]
@abizake Nice solution, right now the latest `serverless-azure-functions` module has `8.11.1` as default node version.

**Comment by bedney** [comment]
This worked for me as well, but really?? I had to do this **in order to make the simplest out-of-the-box 'hello world' example** work from the authors of this plugin (because of the `async` function in that example - this doesn't work with the Azure v1 API which only works with Node 6.X). Very frustrating.
