### ISSUE TITLE
Discuss: need to use x-azure-settings?

### ISSUE THREAD

**Issue by christopheranderson** [serverless/serverless-azure-functions#12]
One thing that has occurred to me as I use the tooling is that the x-azure-settings stuff and the way we do bindings is a bit odd. I looked at other providers and they don't bother with separating out their special settings - could we provide a more optimal experience by just skipping the "x-azure" stuff?

**Comment by lostintangent** [comment]
+1! I would love to see the prefix removed as well.

**Comment by tbarlow12** [comment]
Closing in favor of duplicate #371
