### ISSUE TITLE
Node quickstart deployment fails

### ISSUE THREAD

**Issue by bluebirdtech** [serverless/serverless-azure-functions#125]
### Steps
* Created a new Azure account
* Followed [the quickstart instructions](https://serverless.com/framework/docs/providers/azure/guide/quick-start/)

### Observed
* Microsoft.Storage/storageAccounts, Microsoft.Web/serverfarms & microsoft.insights/components deployed fine
* Microsoft.Web/sites in deployment has status `Conflict`
  * Operation details/status message:
```
{
  "Code": "Conflict",
  "Message": "Website with given name my-unique-name already exists.",
  "Target": null,
  "Details": [
    {
      "Message": "Website with given name my-unique-name already exists."
    },
    {
      "Code": "Conflict"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "54001",
        "MessageTemplate": "Website with given name {0} already exists.",
        "Parameters": [
          "my-unique-name"
        ],
        "Code": "Conflict",
        "Message": "Website with given name my-unique-name already exists."
      }
    }
  ],
  "Innererror": null
}
```

### Expected
* Deployment works fine

### Tried
* Hacking local install to have [changes in this PR](https://github.com/serverless/serverless-azure-functions/issues/123).  No change.

### Other info
* I'm installing serverless locally first
* Node: 8.11.1, serverless: 1.32.0, serverless-azure-functions: 0.6.0

**Comment by fiveisprime** [comment]
This is an Azure limitation. The name of the app needs to be unique; change it from `"my-unique-name"` to something else like `"my-unique-name98765"` and try again.

**Comment by bluebirdtech** [comment]
OK, thanks @fiveisprime I've got it working now.  I obviously saw that the name needs to be unique, but I didn't for a moment consider it would mean unique across all other users of azure.

Perhaps we can change `my-unique-name` in the examples to `my-unique-across-all-azure-users-name`?  It's a little verbose, but something to that effect that would prevent others getting stuck here?  Though perhaps this is a serverless docs suggestion, more than your plugin.
