### ISSUE TITLE
c# Syntax highlighting breaks with escaped quotes in verbatim string literals

### ISSUE THREAD

**Issue by UpQuark** [serverless/serverless-azure-functions#126]
In the in-browser editor for serverless function code in Azure, the following code:

```
var json = $@"{{
  ""data"": {{
    ""attributes"": {{
      ""transactionID"": ""{chargeId}""
    }}
  }}
}}";
```

...which resolves and compiles correctly to JSON with single double quotes and single brackets, breaks the inline syntax highlighting / compiler on the first double quotation.

![image](https://user-images.githubusercontent.com/2613600/47105592-632df280-d212-11e8-8699-10a1a45133e6.png)

Pretty minor, but figured it was worth a report. It throws off all the inline-corrections for the rest of the file.

**Comment by tbarlow12** [comment]
@UpQuark unrelated to the `serverless-azure-functions` plugin. Closing
