### ISSUE TITLE
Old jsonpath has vulnerable static-eval dependency

### ISSUE THREAD

**Issue by serverlessnomad** [serverless/serverless-azure-functions#130]
"jsonpath": "^0.2.11" leverages the static-eval package which has a sandbox breakout / arbitrary code execution vulnerability.  The latest version of jsonpath includes the patched 2.0.0 version of static-eval that addresses the issue.

https://nodesecurity.io/advisories/548

**Comment by tbarlow12** [comment]
Looks like this was using `v0`. Please try updating your version and let us know if you experience the same thing. Closing for now
