### ISSUE TITLE
How to register binding extension for blob triggers?

### ISSUE THREAD

**Issue by frillamola** [serverless/serverless-azure-functions#132]
After deploying a Nodejs Azure function with a blob trigger using `serverless deploy`, when I try to open it in the Azure portal I get the following message:
`Error: The binding type(s) 'blobTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.`

I read in the Azure documentation:  
`Azure Functions supports HTTP and timer out of the box. To work with other services, you need to install or register a binding extension. Binding extensions are provided via Azure Core Tools or NuGet packages.`

Is it possible to register the binding extension by configuration during serverless deploy?

**Comment by manjuk41** [comment]
I am having same issue. @frillamola  Did you find anything.

**Comment by wbreza** [comment]
@frillamola @manjuk41 You can run `func extensions install` prior to deployment.  This will download and register the required bindings.
