### ISSUE TITLE
support for Azure python functions

### ISSUE THREAD

**Issue by karanrk** [serverless/serverless-azure-functions#133]
Hello Team,

It would be really nice to have python runtime supported for azure functions with serverless. 
Microsoft has made the azure v2 compatible with python3.6. Please have a ticket opened to track this.

Best Regards,
Karan

**Comment by tbarlow12** [comment]
Hi @karanrk, thank you for bringing this up. It is in progress right now and we will publish more documentation as the new version is published. Closing in favor of duplicate: #378 

Also, see PR #362
