### ISSUE TITLE
Add "invoke-local" feature

### ISSUE THREAD

**Issue by christopheranderson** [serverless/serverless-azure-functions#16]
invoke-local is a useful command for quick testing locally 

We've got two options:
 - the azure functions core tooling (windows only for a bit longer)
 - a simple shim, old example here: https://github.com/christopheranderson/azure-functions-node-harness

**Comment by rupakg** [comment]
Till we get this feature, can we print a message "Feature yet to be implemented"? Currently, nothing is printed so it is confusing if the feature worked or not.

**Comment by t-my** [comment]
Currently, with azure-functions-core-tools@core you can host functions locally and thus debug them. Is this possible in the serverless framework? If not, it would be very convenient to have.

**Comment by gavination** [comment]
I've run into some trouble using the serverless plugin in conjunction with the azure-functions-core-tools runtime. Would love for this to be a feature.

**Comment by IamNguele** [comment]
Hey is there any update around this?
