### ISSUE TITLE
How are npm packages included in the deploy?

### ISSUE THREAD

**Issue by HyveMynd** [serverless/serverless-azure-functions#17]
Other than manually uploading the `package.json` and using `npm install` through other dev tools, I have been unable to get this plugin to work when using npm packages. What is the recommended method to install and use npm packages with azure?

**Comment by christopheranderson** [comment]
Could you please provide a repro/example + any error messages you're seeing? Not entirely sure what you might be hitting.

We have published this as a package to npm, so you should be able to just run `npm i -g serverless-azure-functions`. Be sure to use Node v6.5.0 or you may run into some issues.

**Comment by HyveMynd** [comment]
The issues I am running into are not with the local setup. Following the instructions works just fine and I am able to invoke the function with no problem. However as soon as I add an additional package, e.g. `lodash`, and try to import using `const lodash = require('lodash')`  the invocation fails with `Cannot find module 'lodash'`.

I am currently getting around this by uploading the `package.json` into the function directory on azure and running `npm install`. I am wondering if there is another method for getting packages to be bundled or installed with the deploy.

Example repo for reference: https://github.com/HyveMynd/azure-test
Steps to reproduce:
1. clone repo
2. `sls deploy`
3. `sls invoke -f httpjs`
4. Error is in the logs

**Comment by christopheranderson** [comment]
Ah, it's possible we're not packaging things correctly, then. Will take a look at the repro and potentially a fix later today. Thanks for the follow up info & easy repro.

**Comment by HyveMynd** [comment]
Thanks for looking into it. And thank you for the amazing work on this plugin!

**Comment by christopheranderson** [comment]
@pragnagopa - We can include the package.json in the deployment and run a kudu command to npm install. This will avoid conflicting npm issues on install/etc.

Kudu Command API: https://github.com/projectkudu/kudu/wiki/REST-API#command

**Comment by HyveMynd** [comment]
Gave the latest version a go. Everything seems to great! Thanks guys!
