### ISSUE TITLE
"No job functions found." when running locally from azure-nodejs template

### ISSUE THREAD

**Issue by e-compton** [serverless/serverless-azure-functions#249]
I ran the serverless generate to create the template project:
```
serverless create -t azure-nodejs -p azure-function-serverless
```
Then installed:
```
npm install azure-functions-core-tools -g
```
and ran:
```
npm start
```

and got:
```
No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.)
```

It seems to be failing because there aren't any `function.json` files which the `func host start` command expects to exist. But the README file says:
```
Note: The file `{function name}/function.json` is included in the template for the quickstart, but this will be replaced by a generated file from the `serverless-azure-functions` plugin at deployment.
```

It looks like the template project has since changed and the `function.json` files do not exist in the project. Is there any way for me to run my serverless functions locally when setup for Azure? And could the README file be changed so that it is less confusing?

**Comment by rkmusic75** [comment]
Did you find a solution to this ??

**Comment by e-compton** [comment]
I ended up just using the Official Azure Function cli to create my apps instead. `serverless` doesn't seem to support running Azure functions locally at this time.

https://github.com/Azure/azure-functions-core-tools/blob/dev/README.md
