### ISSUE TITLE
Deployement on slot

### ISSUE THREAD

**Issue by stelone** [serverless/serverless-azure-functions#297]
Is deployement on slot plan in version 1.0.0 ? 
slot = stage on AWS

**Comment by tbarlow12** [comment]
@stelone not for `1.0.0`, but soon. Currently, Azure Functions only have one slot available, so it might not be a perfect analog to AWS stage. Currently, this plugin applies the `stage` idea with resource group names. But slot deploy will be coming soon

**Comment by stelone** [comment]
okay thank for informations.
