### ISSUE TITLE
Is there a way to specify output bindings?

### ISSUE THREAD

**Issue by itaym2** [serverless/serverless-azure-functions#33]
Hi,
I am writing a function which needs to output a document to Azure's DocumentDb.  
Azure functions support this feature via output binding (https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-documentdb)
Is there a way to specify the output bindings in serverless.yml?

**Comment by pragnagopa** [comment]
Yes. Here is an example for adding documentDb outputBinding for a [simple http trigger](https://github.com/serverless/examples/tree/master/azure-node-simple-http-endpoint) 

events: 
       - http: true
         x-azure-settings:
           authLevel : anonymous
       - documentDB: 
         x-azure-settings:
           connection: AppSettingSetViaArmTemplate
           createIfNotExists: true  

Please note that connection property under x-azure-settings is the name of app setting that is specified in the ARM template when deploying the function app. You need to provide your own ARM template file for deploying:

provider:
  name: azure
  location: West US
  armTemplate:
     file: YourARMTemplate.json
     parameters:
      VariableNameToUserInArmTemplate: Value

**Comment by itaym2** [comment]
Thanks!
I found some bugs related to the documentDB binding, I will open seperate issues to discuss.
