### ISSUE TITLE
sls should not remove resource group

### ISSUE THREAD

**Issue by stelone** [serverless/serverless-azure-functions#356]
The command  `sls remove` delete resource group, even when the resource group was not create by the framework. 

With parameter `resourceGroup` you can specify an existing one and the resource group can contain other resource which was not create by the template. 
The command should only remove resources created by framework. 

Even when it's resourceGroup is not specify, we should ask if the user want to remove all ressource of the resource group and the resource group.

**Comment by tbarlow12** [comment]
@stelone the `remove` command is mostly for use in experimentation. Many developers will create test function apps when using the tool, and we wanted to provide a quick way to make sure they were cleaning things up when they were finished experimenting. We *do not* recommend its usage for production-level applications. The added complexity of keeping track of which resources were created by the tool is too much for a feature that has such a limited use case is too much to maintain. Closing this issue for now. See feature request #380 for more info
