### ISSUE TITLE
Wrong displayName for documentDB out binding

### ISSUE THREAD

**Issue by itaym2** [serverless/serverless-azure-functions#36]
The displayName property of documentDB out binding in binding.json is currently set to "$documentDB_displayName"  
It should be changed to "$documentDBOut_displayName", otherwise you get a "Binding not supported" error when trying to run "sls deploy" and have documentDB out event in serverless.yml.

**Comment by pragnagopa** [comment]
opened [issue ](https://github.com/Azure/azure-webjobs-sdk-templates/issues/413) to track fixing bindings.json.  If direction is not specified for a binding, it defaults to "out". As a workaround for now, can you remove direction parameter for documentDb in serverless.yml? Let us know if you still run into issues.

**Comment by itaym2** [comment]
Removing the direction parameter from serverless.yml fixed the issue.
