### ISSUE TITLE
Disable CORS during offline testing

### ISSUE THREAD

**Issue by e-compton** [serverless/serverless-azure-functions#365]
# This is a Feature Proposal

## Description

When creating an azure function app it is already possible to set the cors settings in the function itself after it has been deployed. However, there is not currently any way to disable CORS while developing offline.

The underlying program `azure-function-core-tools` does support this feature, so a simple workaround that I've been using so far is to modify config.js inside this package and change funcCoreToolsArgs to:
`funcCoreToolsArgs: ["host", "start", "--cors", "*"],`

However, it would be really useful if this was the default setting. 
# Related Issues
- #360

**Comment by tbarlow12** [comment]
@e-compton I'm hesitant to make that a default setting, but what I did was allow for any additional arguments to be passed to the spawned process by running:

```
sls offline -a "--cors *"
```

I'm sure this issue will crop up with other arguments that could be passed to the process as well, and we want to keep it open and extensible for all developers. About to open a PR with my changes.

**Comment by diegoazh** [comment]
> @e-compton I'm hesitant to make that a default setting, but what I did was allow for any additional arguments to be passed to the spawned process by running:
> 
> ```
> sls offline -a "--cors *"
> ```
> 
> I'm sure this issue will crop up with other arguments that could be passed to the process as well, and we want to keep it open and extensible for all developers. About to open a PR with my changes.

I try to run this command but it throws the following error `additionalArgs.split is not a function`, this command really work?

**Comment by Devlin556** [comment]
Hello @tbarlow12! 
I stuck with the same error as above. 
So, I have two questions:
The first - how can I run functions which trigger with service bus or HTTP? When I run it with `sls offline` - it writes to console output this (I use serverless-offline plugin and typescript) and I cannot see any address to make requests: 

![image](https://user-images.githubusercontent.com/16045765/112635775-4a977d00-8e4d-11eb-908d-7f432830812e.png)
The second - when I run it with `sls offline -a "--typescript *"` I see the error from the above comment:

![image](https://user-images.githubusercontent.com/16045765/112635970-86324700-8e4d-11eb-837b-6057608ca24a.png)

On the deployed version - it works fine.

Thanks!
