### ISSUE TITLE
Service Plan Config not being applied

### ISSUE THREAD

**Issue by Rapol** [serverless/serverless-azure-functions#388]
# This is a Bug Report

## Description

- What went wrong?

Deploying a Premium App function always defaults the Sku Name and Tier to EP1 and ElasticPremium
- What did you expect should have happened?

Able to set the App Service Plan Sku and Tier via the provider config field called appServicePlan
- What was the config you used?

```
provider:
  name: azure
  ...
  type: premium
  appServicePlan:
    sku:
      tier: PremiumV2
      name: P1v2
```

- What stacktrace or error message from your provider did you see?

In our case, it fails because we cannot deploy ElasticPremium in our RG
`The pricing tier 'ElasticPremium' is not allowed in this resource group. Use this link to learn more: http://go.microsoft.com/fwlink/?LinkId=825764`

## Additional Data

After going through the code, we found that there's a typo in src/armTemplates/resources/appServicePlan.ts line 71:

```
const resourceConfig: ResourceConfig = {
      sku: {},
      ...config.provider.storageAccount,
    };
```
config.provider.storageAccount should be config.provider.appServicePlan

After fixing the typo locally in my node modules, I was able to set the tier and name of the service plan.

**Comment by wbreza** [comment]
Should be resolved with #386. Please try our latest NPM with the @beta tag to verify.

**Comment by Rapol** [comment]
Sweet, thanks! Will look at dev branch before opening tickets in the future.

**Comment by wbreza** [comment]
@Rapol not a problem. We’ll post a new official release next week.
