### ISSUE TITLE
First deployment fails

### ISSUE THREAD

**Issue by juhamust** [serverless/serverless-azure-functions#39]
Deploy fails at first attempt. Second works without any modifications:
```

10:31:04 juha@bllt server master ? sls deploy
Serverless: Packaging service...
Serverless: Logging in to Azure
Serverless: Creating resource group: example-service-rg
Serverless: Creating function app: example-service
Serverless: Waiting for Kudu endpoint...
Serverless: Parsing Azure Functions Bindings.json...
Serverless: Building binding for function: messages event: httpTrigger
Serverless: Packaging function: messages

  Error --------------------------------------------------

     getaddrinfo ENOTFOUND example-service.scm.azurewebsites.net example-service.scm.azurewebsites.net:443

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.5.0
     Serverless Version: 1.8.0

10:41:41 juha@bllt server master ? sls deploy
Serverless: Packaging service...
Serverless: Logging in to Azure
Serverless: Looking for deployed functions that are not part of the current deployment...
Serverless: Creating resource group: example-service-rg
Serverless: Creating function app: example-service
Serverless: Waiting for Kudu endpoint...
Serverless: Parsing Azure Functions Bindings.json...
Serverless: Building binding for function: messages event: httpTrigger
Serverless: Packaging function: messages
Serverless: Syncing Triggers....Response statuscode: 200
Serverless: Running Kudu command del package.json...
Serverless: Running Kudu command npm install --production...
Serverless: Successfully created Function App
```
Not sure if the problem is in Serverless or Azure?

**Comment by pragnagopa** [comment]
This is a know DNS resolution issue with Azure. Let us know if this is happening consistently. So far we have only seen this repor intermittently.

**Comment by hardik-shah-28** [comment]
Hi @pragnagopa when I am running sls deploy command it gives me one code and open up aure window in new tab I put that code it authenticates me and then my machine freezes it does nothing. I got this error for almost around 30 times. i would really appreciate if you can please help me out.
![freezes](https://user-images.githubusercontent.com/25598255/27705144-4465df3e-5cca-11e7-94ba-5a028354a55d.png)

**Comment by lostintangent** [comment]
@hardik-shah-28 This issue should have been resolved. Are you still experiencing it?

**Comment by juhamust** [comment]
I'm not currently working with Azure Functions, so if someone with recent version of plugin could verify this, it would be awesome 👍

**Comment by joakimgrr** [comment]
Just created a fresh Azure Functions project. The first "sls deploy" failed, but the second one worked without any changes or errors.

Some general (slim) information:
OS:                     darwin
Node Version:           8.4.0
Serverless Version:     1.24.1

If there is any tests i could try / further information to provide, i'd be happy to.

**Comment by artoliukkonen** [comment]
Confirming that this is still happening. Just deployed my first Azure function, got the same "ENOTFOUND" error, google'd that, ended up here and tried running deploy second time which worked fine. 

     OS:                     darwin
     Node Version:           6.10.3
     Serverless Version:     1.26.1

**Comment by ppptrevoro** [comment]
This was happening to me and setting my DNS server to google's 8.8.8.8 fixed it for me.

MacOS
