### ISSUE TITLE
SLS Offline don't run webpack build with TypeScript

### ISSUE THREAD

**Issue by s-stefanov** [serverless/serverless-azure-functions#392]
# This is a Bug Report

## Description

- What went wrong?
Having SLS project with TypeScript and Webpack. Webpack build didn't run before `sls offline` invoke. When I invoke `sls package`, the functions are transpiled and packaged
- What did you expect should have happened?
Webpack build should run before `func host start`
- What was the config you used?
Uploading my three configs
https://pastebin.com/gizzsRZQ - serverless.yml
https://pastebin.com/86LGJyZF - webpack.config.js
https://pastebin.com/iPTfqUNw - .babelrc
- What stacktrace or error message from your provider did you see?
0 functions found. The `function.json` is generated, but it points to not existed .js file

Similar or dependent issues:

- #12345

## Additional Data

- **_Serverless Framework Version you're using_**:
1.49
- **_Serverless CLI Version you're using_**:
- **_Serverless Azure Plugin Version you're using_**:
1.0.2
- **_Operating System_**:
MacOS 10.14
- **_Stack Trace_**:
- **_Provider Error messages_**:

**Comment by tbarlow12** [comment]
We have not added support for TypeScript just yet. It's on the roadmap. #366

**Comment by s-stefanov** [comment]
Yes, I understand that. But when I run `sls deploy` or `sls package` the correct zip file is created and uploaded to Azure. Functions are executed correctly.
My problem is to run Webpack build on local `sls offline` before `func host start` command. Can this be made?

**Comment by s-stefanov** [comment]
@tbarlow12 The same issue is with modern JavaScript syntax and babel/webpack build to support it. On SLS offline there is no support of it.

**Comment by cyppher** [comment]
@tbarlow12 We have written our functions in ES6+ including ES-modules (`import`). 
Running `sls deploy` does in fact transpile code perfectly, however `sls offline` gives us Javascript errors about not supported ES6 code (such as import / export).

How can we run `sls offline` and make sure Webpack / Babel is transpiling code as it does with `sls deploy`?
