### ISSUE TITLE
Add call to sync triggers api

### ISSUE THREAD

**Issue by pragnagopa** [serverless/serverless-azure-functions#4]
Add call to sync triggers api after uploading function code. This is blocked right now due to a bug in Kudu that blocks service principal user from calling SyncTriggers api.

**Comment by mi-hol** [comment]
@pragnagopa would you have the bug number reference to https://github.com/projectkudu/kudu/issues for this bug?

**Comment by pragnagopa** [comment]
@mi-hol - Issue is fixed now. No tracking bug. Need to wait for the fix to be deployed. Approximate timeline a month from now.

**Comment by pragnagopa** [comment]
Update requestUrl in [syncTriggers](https://github.com/serverless/serverless-azure-functions/blob/dev/provider/azureProvider.js#L478 ) to https://<functionAppName>.scm.azurewebsites.net/api/functions/synctriggers
once the fix for Service principal issue gets deployed

**Comment by ConnorMcMahon** [comment]
Some customers in this [thread](https://github.com/Azure/azure-functions-host/issues/2421) are expressing their desire to have triggers synchronized in the kudu workflow. How much work would it be to add this?

**Comment by jwisener** [comment]
Is this issue still open"? since 2017? We are experiencing this type of issue as well.
