### ISSUE TITLE
Hello World deployment fails

### ISSUE THREAD

**Issue by hswee** [serverless/serverless-azure-functions#40]
Following the steps [here](https://serverless.com/framework/docs/providers/azure/examples/hello-world/node/), I'm getting an error on the deploy step.
(As an aside, step 2 on the above page says `npm install -g serverless-azure` which I guess should be `npm install -g serverless-azure-functions`)
I've also followed the setup steps from [here](https://serverless.com/framework/docs/providers/azure/guide/credentials/)

I'd appreciate any help you could give. Thanks!

Trace below:
> Serverless: Packaging service...
> Serverless: Logging in to Azure
> Serverless: Looking for deployed functions that are not part of the current deployment...
> Serverless: Creating resource group: azure-example-rg
> Serverless: Creating function app: azure-example
>  
>   Error --------------------------------------------------
>  
>      Long running operation failed with error: 'At least
>      one resource deployment operation failed. Please list
>      deployment operations for details. Please see https://aka.ms/arm-debug
>      for usage details.'.
>  
>      For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
>  
>   Stack Trace --------------------------------------------
>  
> Error: Long running operation failed with error: 'At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.'.
>     at PollingState.getCloudError (/home/excelian/source/test-serverless/azure-example/node_modules/ms-rest-azure/lib/pollingState.js:126:15)
>     at /home/excelian/source/test-serverless/azure-example/node_modules/ms-rest-azure/lib/azureServiceClient.js:173:38
>     at Object.async.whilst (/home/excelian/source/test-serverless/azure-example/node_modules/ms-rest-azure/node_modules/async/lib/async.js:621:13)
>     at /home/excelian/source/test-serverless/azure-example/node_modules/ms-rest-azure/node_modules/async/lib/async.js:617:23
>     at /home/excelian/source/test-serverless/azure-example/node_modules/ms-rest-azure/lib/azureServiceClient.js:146:20
>     at /home/excelian/source/test-serverless/azure-example/node_modules/ms-rest-azure/lib/azureServiceClient.js:212:5
>     at /home/excelian/source/test-serverless/azure-example/node_modules/ms-rest-azure/lib/azureServiceClient.js:346:12
>     at retryCallback (/home/excelian/source/test-serverless/azure-example/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:85:9)
>     at retryCallback (/home/excelian/source/test-serverless/azure-example/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:135:9)
>     at handleRedirect (/home/excelian/source/test-serverless/azure-example/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
>     at Request._callback (/home/excelian/source/test-serverless/azure-example/node_modules/ms-rest/lib/requestPipeline.js:126:16)
>     at Request.self.callback (/home/excelian/source/test-serverless/azure-example/node_modules/ms-rest/node_modules/request/request.js:187:22)
>     at emitTwo (events.js:106:13)
>     at Request.emit (events.js:191:7)
>     at Request.<anonymous> (/home/excelian/source/test-serverless/azure-example/node_modules/ms-rest/node_modules/request/request.js:1044:10)
>     at emitOne (events.js:101:20)
>     at Request.emit (events.js:188:7)
>     at IncomingMessage.<anonymous> (/home/excelian/source/test-serverless/azure-example/node_modules/ms-rest/node_modules/request/request.js:965:12)
>     at emitNone (events.js:91:20)
>     at IncomingMessage.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
> From previous event:
>     at PluginManager.run (/home/excelian/.nvm/versions/node/v6.5.0/lib/node_modules/serverless/lib/classes/PluginManager.js:156:22)
>     at Serverless.run (/home/excelian/.nvm/versions/node/v6.5.0/lib/node_modules/serverless/lib/Serverless.js:95:31)
>     at serverless.init.then (/home/excelian/.nvm/versions/node/v6.5.0/lib/node_modules/serverless/bin/serverless:23:50)
>     at process._tickCallback (internal/process/next_tick.js:103:7)
>  
>   Get Support --------------------------------------------
>      Docs:          docs.serverless.com
>      Bugs:          github.com/serverless/serverless/issues
>  
>      Please report this error. We think it might be a bug.
>  
>   Your Environment Information -----------------------------
>      OS:                 linux
>      Node Version:       6.5.0
>      Serverless Version: 1.9.0
>

**Comment by hswee** [comment]
Running `sls deploy list` gives:

>   Serverless Error ---------------------------------------
>  
>      The command you entered did not catch on any hooks
>  
>   Stack Trace --------------------------------------------
>  
> ServerlessError: The command you entered did not catch on any hooks
>     at PluginManager.run (/home/excelian/.nvm/versions/node/v6.5.0/lib/node_modules/serverless/lib/classes/PluginManager.js:153:13)
>     at Serverless.run (/home/excelian/.nvm/versions/node/v6.5.0/lib/node_modules/serverless/lib/Serverless.js:95:31)
>     at serverless.init.then (/home/excelian/.nvm/versions/node/v6.5.0/lib/node_modules/serverless/bin/serverless:23:50)
>     at process._tickCallback (internal/process/next_tick.js:103:7)
> From previous event:
>     at runCallback (timers.js:574:20)
>     at tryOnImmediate (timers.js:554:5)
>     at processImmediate [as _immediateCallback] (timers.js:533:5)
> From previous event:
>     at __dirname (/home/excelian/.nvm/versions/node/v6.5.0/lib/node_modules/serverless/bin/serverless:15:28)
>     at Object.<anonymous> (/home/excelian/.nvm/versions/node/v6.5.0/lib/node_modules/serverless/bin/serverless:27:4)
>     at Module._compile (module.js:556:32)
>     at Object.Module._extensions..js (module.js:565:10)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
>     at Module.runMain (module.js:590:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3
>  
>   Get Support --------------------------------------------
>      Docs:          docs.serverless.com
>      Bugs:          github.com/serverless/serverless/issues
>  
>   Your Environment Information -----------------------------
>      OS:                 linux
>      Node Version:       6.5.0
>      Serverless Version: 1.9.0
>

**Comment by pragnagopa** [comment]
We do not have support for sls deploy list yet. Please refer to [docs](https://serverless.com/framework/docs/providers/azure/cli-reference/) for list of supported commands.
Regarding deployment failure, its possible that name you provided:azure-example for the azure function app is already in use.  Can you please check [here ](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-common-deployment-errors)to for more detailed error message?

**Comment by hswee** [comment]
You were right, it was the name not being unique, although the reason for the error wasn't listed anywhere in azure's activity log. Thank you for the help!

**Comment by justinmchase** [comment]
So the app name has to be globally unique? It would be really nice if this was called out during creation or if the error message was a little more clear.
