### ISSUE TITLE
Function App not ready?

### ISSUE THREAD

**Issue by diego1686** [serverless/serverless-azure-functions#409]
Hi there! I'm very new on Azure functions world, so sorry if this question is obvious for some of you guys.

I'm trying to deploy a function and I'm getting this:

```
Serverless: Deployed serverless functions:
Serverless: -> Function App not ready. Retry 0 of 30...
Serverless: -> Function App not ready. Retry 1 of 30...
Serverless: -> Function App not ready. Retry 2 of 30...
Serverless: -> Function App not ready. Retry 3 of 30...
Serverless: -> Function App not ready. Retry 4 of 30...
Serverless: -> Function App not ready. Retry 5 of 30...
Serverless: -> Function App not ready. Retry 6 of 30...
```

This continues until 30, and the function finally is not deployed. Can anybody explain me what's happening? First I deployed a dummy function with just a `context.log` and it worked fine, but since I added npm modules and some logic to the function, I'm getting this.

runtime: nodejs10.x

**Comment by hyperyn** [comment]
Can confirm that we're seeing the same thing. The problem is intermittent, even when using the same configuration between deploys.

**Comment by diego1686** [comment]
Closing this. The issue was happening because the handler path was wrong. Maybe the console output should be improved, but anyway there is no bug at all. Sorry.
