### ISSUE TITLE
Deploy single function (quickly)

### ISSUE THREAD

**Issue by Stewartarmbrecht** [serverless/serverless-azure-functions#41]
Is this possible?  I noticed that is I set the -f parameter to the name of a function it still deployed the entire service.

example: sls deploy -f registerUser

Still gets this:
Serverless: Packaging service...
Serverless: Logging in to Azure
Serverless: Looking for deployed functions that are not part of the current deployment...
Serverless: Creating resource group: tococms-sf-rg
Serverless: Creating function app: tococms-sf
Serverless: Waiting for Kudu endpoint...
Serverless: Parsing Azure Functions Bindings.json...
Serverless: Building binding for function: registerUser event: httpTrigger
Serverless: Packaging function: registerUser
Serverless: Building binding for function: queuejs event: queueTrigger
Serverless: Building binding for function: queuejs event: blob
Serverless: Packaging function: queuejs
Serverless: Syncing Triggers....Response statuscode: 200
Serverless: Running Kudu command del package.json...
Serverless: Running Kudu command npm install --production...
Serverless: Successfully created Function App

I have also noticed that the -n flag (No Deploy) does not work either.

**Comment by pragnagopa** [comment]
Here is the right [command](https://serverless.com/framework/docs/providers/azure/cli-reference/deploy-function/):
sls deploy function -f registerUser

**Comment by Stewartarmbrecht** [comment]
That worked.  Thanks!
