### ISSUE TITLE
Update templates to target ~3 (includes Node 12)

### ISSUE THREAD

**Issue by jeffhollan** [serverless/serverless-azure-functions#414]
Today this creates apps targeting ~2 for the functions runtime version.  This also limits it to node 8 and node 12.  If we updated to ~3 it would target node 10 or node 12 (current supported LTS versions)

**Comment by tbarlow12** [comment]
I'll leave this open for now, but the templates are actually in [serverless core](https://github.com/serverless/serverless). Thanks for the reminder.

**Comment by tbarlow12** [comment]
But you are right to include this here for the version limiting. That is controlled within the plugin
