### ISSUE TITLE
Allow specification of resource group in serverless.yaml

### ISSUE THREAD

**Issue by aidanmorgan** [serverless/serverless-azure-functions#44]
The current experience of automatically creating an Azure resource group for each function is a great "out of the box" experience, however when you are deploying a lot of different functions it would be nice to be able to specify the name of the resource group to use in the serverless.yaml file.

Perhaps something like this:

service: my-example-service
x-azure-resource-group: special-resource-group

I am happy to submit a PR with this change if people are okay with the suggestion.

**Comment by aidanmorgan** [comment]
Alternatively this might be better placed in the provider configuration in the serverless.yaml file?

provider:
  name: azure
  location: Australia East
  resource-group: special-resource-group

**Comment by lostintangent** [comment]
@aidanmorgan This suggestion sounds great to me!

**Comment by aidanmorgan** [comment]
I have implemented it as a resourceGroup item under the provider definition and it seems to work quite well.

**Comment by cmatskas** [comment]
@aidanmorgan is this in one of the pending PRs? I'd love to use this as I think hardcoding the RG name is a bad idea or at least having an option to override would be much better.

**Comment by aidanmorgan** [comment]
@cmatskas I have an implementation of it on a branch, however I am still not comfortable with the default behaviour being to delete the resource group - i think RG's should probably be deleted manually.

There's also some cross-cutting concerns with other functions that are deployed, the implementation I have is not fully tested yet - hopefully I should have some time this weekend to finish it off.

**Comment by cmatskas** [comment]
@aidanmorgan you mean when you run the `serverless remove` command? Yes, this is a grave issue indeed. The needs to be a more granular to allow to either blast the whole thing or remove just the function within the RG. You've already raised this in #48 which is great so hopefully we'll see these changes soon

**Comment by aidanmorgan** [comment]
@cmatskas there is also an issue with "replacing" an existing function, the codebase has assumptions that there is only one function deployed in the function app, so it deletes everything - so I've had to rework a lot of that logic as well.

**Comment by cmatskas** [comment]
@aidanmorgan is this tracked separately? I believe this is an important addition. Devs will need control at resource group, function app (resource) and function level as well

**Comment by aidanmorgan** [comment]
I originally submitted the code in 1 PR, but have cancelled that one and will be submitting several smaller ones - will hopefully get some time on Saturday to get it finished off.

**Comment by cmatskas** [comment]
@aidanmorgan good luck :)

**Comment by aidanmorgan** [comment]
@cmatskas I've pushed my working changes into my fork, the create/remove semantics work, but it requires more testing before I create a PR.

https://github.com/aidanmorgan/serverless-azure-functions/tree/issue-44

It works for two different serverless definitions deploying to the same function app - for deploying and removing.

**Comment by cmatskas** [comment]
Great effort. I only hope I didn't add any pressure BTW :) I would feel really bad if that was the case.

**Comment by aidanmorgan** [comment]
@cmatskas not at all, it just required me to not be lazy and actually push my changes to my fork.

I'd love any feedback/suggestions you may have!

**Comment by aidanmorgan** [comment]
@cmatskas did you get a chance to give my changes a run? I did some testing on the weekend and it worked for the use cases I have.

**Comment by jeevan-shikaram** [comment]
Bump. I'd like to specify which resource group my function gets deployed to so that I can keep all of my projects contained inside these groups.

What's the status on this @cmatskas ?

**Comment by miguelguadarrama** [comment]
Any update on this? This would be really useful for me right now. I'm not azure admin, so creating resource groups is not something my user can do. I would need to ask the admin to create a resource group with the name serverless would generate, ugh.

**Comment by jeevan-shikaram** [comment]
@miguelguadarrama I was able to change the resource group name in the node modules folder.
in serverless-azure-functions/provider/azureProvider.js.
Line: "resourceGroupName = `${functionAppName}-rg`;"
Then you need to delete the line that creates the resource group.

This is obviously not ideal but it is a quick workaround. If you delete the node modules folder it will be reset.

**Comment by miguelguadarrama** [comment]
Ah sounds good @jeevan-shikaram ! Just one question, deploying removes and recreates the function apps (which I don't mind) but does it mess with something else in that resource group?

**Comment by jeevan-shikaram** [comment]
@miguelguadarrama I haven't really noticed that, have a look at the deployment function to see if it removes anything else. I think it doesn't as I had a power bi instance going. Check to make sure.

**Comment by ihachani** [comment]
Any update on this?

**Comment by webjay** [comment]
I am building for a big organization and can not create my own ressource group, so I also need this.

**Comment by wkirby** [comment]
@webjay This turned out to be really straightforward to implement. You can pull our fork which allows you to define a resource group in the provider block. We haven't experienced any issues in the last 2 weeks or so, and we plan to open a pull request soon (pending more testing):

```
provider:
  name: azure
  resource-group: your-resource-group
```

Fork is here: https://github.com/apsislabs/serverless-azure-functions

**Comment by wkirby** [comment]
Opened a PR with our changes in #119
