### ISSUE TITLE
What's the required version of node and sls in for Python deployments to Azure Functions?

### ISSUE THREAD

**Issue by konradsemsch** [serverless/serverless-azure-functions#459]
I've tried tried already node 6, 10 and 12 and none of them were successful. On the main installation guide is says that node v6.5.0 is required (l[ink](https://www.serverless.com/framework/docs/providers/azure/guide/installation/)), but isn't this outdated?

With this version of node even the `serverless-azure-functions` does not want to install. Could you please provide some guidance?

**Comment by tbarlow12** [comment]
Hi @konradsemsch. Yeah, those docs are outdated. Python support is still in beta, but we're hoping to get a `v2` release out soon. Make sure you use `npm i serverless-azure-functions@beta` when you install the package

**Comment by tbarlow12** [comment]
@konradsemsch the python support is now in the GA release. Please reach out if you have other questions
