### ISSUE TITLE
Provider is created too early in Serverless process, not all variables have been substituted yet

### ISSUE THREAD

**Issue by aidanmorgan** [serverless/serverless-azure-functions#53]
I would like to be able to have some of the setting values derived from the stage option, however at the moment the AzureProvider instance is created too early on in the initialisation of the framework, which means I can't access these options - additionally the framework has not performed variable substitutions yet (as per [Serverless Variables](https://serverless.com/framework/docs/providers/aws/guide/variables/)).

**Comment by fiveisprime** [comment]
@pragnagopa looks like this was this fixed in #54 and #56. Can this be closed or
were you still investigating potential changes to initialization?

**Comment by aidanmorgan** [comment]
@fiveisprime if I understand correctly this has been merged to dev already
