### ISSUE TITLE
Deploy connects to wrong URL

### ISSUE THREAD

**Issue by Jameskmonger** [serverless/serverless-azure-functions#55]
I have followed the [Azure guide](https://serverless.com/framework/docs/providers/azure/guide/) about deployment, and have created an app registration called "serverlesstest":

`azure ad sp create -n serverlesstest -p 'MY PASSWORD HERE'`

In `getDeployedFunctionsNames` in `serverless-azure-functions`, the system then calls to `https://serverlesstest.scm.azurewebsites.net/api/functions` which times out.

I have opened the "App registrations" section on Azure and I can see my `serverlesstest` app there. When I open it up, I see that the home page is `http://serverlesstest` which I think could be causing the problem.

**Comment by cmatskas** [comment]
@Jameskmonger The correct command to create a Service Principal is:
`azure ad app create -n exampleapp --home-page https://test.com --identifier-uris https://test.com -p #1234a$%pwd07`

The app registration and subsequent service principal have nothing to do with the Function name and URI. I hope this makes sense

**Comment by lostintangent** [comment]
I'm going to close this issue now that we've revamped the login process (and docs) to be simpler (and not require a service principal). If you're still running into an issue here, please reopen this. Thanks!
