### ISSUE TITLE
Unable to deploy - clientId must be a non empty string.

### ISSUE THREAD

**Issue by WonderPanda** [serverless/serverless-azure-functions#58]
I followed all the instructions in the readme but when it comes to running `serverless deploy` the operation fails with only the cryptic message:

` clientId must be a non empty string.`

I've confirmed with Powershell that all of the expected environment variables have been set. Any thoughts on why this isn't working for me?

```


  Error --------------------------------------------------

     clientId must be a non empty string.

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                 win32
     Node Version:       6.9.5
     Serverless Version: 1.11.0

```

**Comment by codepunkt** [comment]
Having the same issue.

```
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.2.0
     Serverless Version: 1.11.0
```

**Comment by Gerald-Kodz** [comment]
Same problem

**Comment by WonderPanda** [comment]
@Gerald-Kodz Unfortunately no, I haven't been able to get this working. Waiting for feedback from the team right now.

**Comment by lostintangent** [comment]
@WonderPanda Could you try changing the "service" property in your serverless.yaml file to something really unique and try deploying again? (e.g. wonder-panda-1234)

I'll look into this more deeply, but I just wanted to rule out if the issue is due to a naming conflict. Thanks!

**Comment by WonderPanda** [comment]
@lostintangent Thanks for getting back to me. I tried setting the service name in serverless.yaml to something super obscure: effective-octo-umbrella-test-123 and it still fails with the same error as before.

**Comment by lostintangent** [comment]
@WonderPanda OK cool, thanks for confirming that. From what I can tell, the issue is related to the `azureServicePrincipalClientId` environment variable not being set. Could you confirm that it is? I just tried reproing this issue, and if I remove the `azureServicePrincipalClientId` environment variable, I see the same error message. However, once I set it again, the `deploy` command works perfectly.

**Comment by pragnagopa** [comment]
I cannot repro this either. @WonderPanda can you confirm if you have set environment variables listed [here](https://serverless.com/framework/docs/providers/azure/guide/credentials/)

**Comment by cmatskas** [comment]
It's important to clarify that when you set the environment variables, they are only valid for the current session. If you close down your CLI (bash/npm/cmd) then the variables go with it. Every time you want to use Serverless you need to set the variable again. Alternatively, you can set them up at user or machine level but it's dangerous, considering you'll be storing your SP credentials in clear text

**Comment by pragnagopa** [comment]
We have a [PR ](https://github.com/serverless/serverless-azure-functions/pull/59 ) out to add support for interactive login. This should improve login exeperince.

**Comment by WonderPanda** [comment]
Hey sorry guys, I didn't get back around to playing with this for a bit. Can confirm that I was able to get it working by setting environment variables again. Thought I had it the first time but must have closed my terminal and lost them.

Looking forward to interactive login though!

**Comment by cmatskas** [comment]
Thanks for he update :)

**Comment by lostintangent** [comment]
@WonderPanda That's awesome! Thanks for confirming that fixed it.
