### ISSUE TITLE
Make the HttpTrigger code consistent with the Azure CLI

### ISSUE THREAD

**Issue by cmatskas** [serverless/serverless-azure-functions#64]
When creating a new Azure Function using the serverless commands, the code is slightly inconsistent with what the Azure Functions CLI emits. I would urge that we make these 2 consistent by changing the emitted code to the following:

```
module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');

    if (req.query.name || (req.body && req.body.name)) {
        context.res = {
            // status: 200, /* Defaults to 200 */
            body: "Hello " + (req.query.name || req.body.name)
        };
    }
    else {
        context.res = {
            status: 400,
            body: "Please pass a name on the query string or in the request body"
        };
    }
    context.done();
};
```
If you're happy with this, then I can send you a PR with the changes.
Thanks

**Comment by pragnagopa** [comment]
Current implementation specifically looks for entry point in the js code.  We can address this once #34 is fixed.

**Comment by cmatskas** [comment]
It was more about the contents rather than the files. Is this still dependent on #34 then?

**Comment by pragnagopa** [comment]
Are you referring sample code [here](https://github.com/Azure/boilerplate-azurefunctions)? Serverless plugin just copies the code given by the user and does not have any built-in tempates.

**Comment by cmatskas** [comment]
Yes. I'm referring to the `serverless create` command. The boiler plate code should be consistent IMHO

**Comment by pragnagopa** [comment]
Go ahead an open a PR in [boilerplate-azurefunctions](https://github.com/Azure/boilerplate-azurefunctions) to update the code. As long as it has a function name defined it should be OK.

**Comment by cmatskas** [comment]
Hi @pragnagopa. It seems that the code in boilerplate-azurefunctions is correct but different to the code generated from `serverless create`. I'm trying to work out what template you use to create the basic HTTP trigger function and I haven't been successful as yet. If you could point me to the right direction, I'll be more than happy to raise a PR. Thanks again

**Comment by pragnagopa** [comment]
I misunderstood that you were using boilerplate repo. Here is the code for azure-nodejs [template](https://github.com/serverless/serverless/tree/7d43fa1bae1120516b833316e41489dbcd15ed4c/lib/plugins/create/templates/azure-nodejs). Please submit a PR to [Serverless CLI ](https://github.com/serverless/serverless)repo

**Comment by cmatskas** [comment]
Raised on the right repo. Closing this one for now
