### ISSUE TITLE
Fix CI setup. Ensure working builds

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless-azure-functions#645]
To follow up with maintenance we need to fix CI.

Ideally, if we create a similar configuration as it's in the Serverless Framework -> https://github.com/serverless/serverless/tree/main/.github/workflows where we have three jobs:
- __validate__ - Validates PR's only, by running lint and unit tests
- __integrate__ - Which validates `master` by running unit and integration tests (if they exist - here I believe we can skip on that), and publishes new tag if detects changes of version in package.json
- __publish__ - Runs on version tag, publishes new version to npm

**Comment by medikoo** [comment]
Reopened as we still miss `integrate` build that publishes a new tag.

I see that there are some old integration jobs configured, but they do not seem to be triggered at all, and may no longer be valid. So we need to revisit them and put them into shape

**Comment by gligorkot** [comment]
@medikoo I tried fixing the integration tests, but these require an Azure subscription and I think the subscription set up within this repository might not be paid/up to date or something so they are failing. I've got something that I think might work, but I don't have a subscription to test them on.

**Comment by medikoo** [comment]
@gligorkot thanks for info, in light of that (as I don't have available Azure subscription which can be used for testing), can we update the `integration` workflow to simply run validation tests as it's done in `validation` job?

**Comment by gligorkot** [comment]
@medikoo, I have raised PR #656 to close off this job, then I suggest we deploy a version 2.2.0 so people can start using node 18 support, while next we upgrade any outdated packages and then release a version 3.0.0 - what do you think?
