### ISSUE TITLE
Release of new changes

### ISSUE THREAD

**Issue by nhalstead** [serverless/serverless-azure-functions#654]
There have been changes made to the repo that still needs to be released. This includes the support for Node18 runtime that Azure has supported and was added to this repo but has yet to be released.

Diff: https://github.com/serverless/serverless-azure-functions/compare/f1c480f65d2cbe4f4682d2a154e755cc651bf7d6..master

**Comment by AndyM1H** [comment]
Totally agree. Is it possible to know when the new release will be? Azure will deprecate NodeJS 14 on April 30.

**Comment by caltuco** [comment]
We are facing the possibility to changes our deployments with Terraform, we need to use Node18 and right now we're stuck with the serverless framework.

**Comment by nhalstead** [comment]
Hi @gligorkot, Can you make a release for the changes to this package?

**Comment by gligorkot** [comment]
Hi @nhalstead, unfortunately I can't... I was working with @medikoo to help get the package released as we need it as well, I think the last step is to get #653 merged in which addresses @medikoo's requirements outlined in #645, but I haven't heard from him lately.

What we've done in the meantime on our stack is, we use `patch-package` https://www.npmjs.com/package/patch-package and apply this patch on top of 2.1.3 to support Node 18. You'd still need to use extension version v4 as explained in here to support Node 18 as well. https://github.com/serverless/serverless-azure-functions/issues/592#issuecomment-1288130494 

[serverless-azure-functions+2.1.3.patch](https://github.com/serverless/serverless-azure-functions/files/11196284/serverless-azure-functions%2B2.1.3.patch)

Hope the above helps get you moving and we can get a new release out soon.

**Comment by medikoo** [comment]
All we need to publish a new release is an _integration_ job setup in CI. Please see my comment in #645 

I will also be happy to give a maintenance rights to anyone interested (but first let's get through few submissions together)

**Comment by gligorkot** [comment]
Version 2.2.0 is out now with Node 16 and 18 support!

**Comment by medikoo** [comment]
@gligorkot I've just checked the CI output, and one thing that worries me is list of published files:

```
npm notice 
npm notice 📦  serverless-azure-functions@2.2.0
npm notice === Tarball Contents === 
npm notice 1.1kB  LICENSE     
npm notice 14.2kB README.md   
npm notice 3.4kB  package.json
npm notice === Tarball Details === 
npm notice name:          serverless-azure-functions              
npm notice version:       2.2.0                                   
npm notice filename:      serverless-azure-functions-2.2.0.tgz    
npm notice package size:  6.9 kB                                  
npm notice unpacked size: 18.6 kB                                 
npm notice shasum:        c61b3690e396c05b73bf40096ca5e93c2f0dd042
npm notice integrity:     sha512-Byq3so3WIYQ+u[...]WD2LXW4KfTEGA==
npm notice total files:   3                                       
npm notice 
npm notice Publishing to https://registry.npmjs.org/ with tag latest and default access
```

It feels that no real logic was included, and empty (broken) realesa was just published (I think it can be debugged locally by running `npm pack` as that would generate tar without publish attempt)

**Comment by gligorkot** [comment]
Oh @medikoo that's no good, ok, I'll give it a go locally and see if I can resolve

**Comment by medikoo** [comment]
As I checked, the cause is here: https://github.com/serverless/serverless-azure-functions/blob/dfeb0c5cdff19fd5eb38f35c9fbd3b423bda4af3/package.json#L44-L46

I strongly suggest to revert from _allow list_ approach (remove `files` setting in `package.json`) and instead rely on _deny list_ (configured in `.npmrc).

I remember we faced one similar issue in Framework deployment, where some important files failed to be included in the package, producing broken release.

In packages I maintain, I also issue tests against `npm pack` result -> https://github.com/medikoo/github-actions-workflows/blob/9009d668cf21e399ed67764af59c22120e34b97f/.github/workflows/8-validate.yml#L88-L129
It might be worthwhile to add such tests in CI here

**Comment by gligorkot** [comment]
@medikoo I saw that I had missed a build package step in the publish script - I just added it here to this PR #665 https://github.com/serverless/serverless-azure-functions/pull/665/commits/98ce406b93ee9cb5e6b390aeeaeaa0bc7090c3b8 do you mind having a look please?

**Comment by gligorkot** [comment]
@medikoo tested locally after running `npm run build` and then `npm pack` I see all the files in the output correctly. I think it should be good to go now.

**Comment by gligorkot** [comment]
@medikoo looks like it has worked after the updates. v2.2.1 is out.

**Comment by medikoo** [comment]
@gligorkot great to hear that 🎉
