### ISSUE TITLE
Unable to install in Powershell

### ISSUE THREAD

**Issue by fiveisprime** [serverless/serverless-azure-functions#66]
I cannot get `keytar` to install in Powershell. I spent a couple of hours trying to make it work (following the guides from rvagg) then tried in cmd out of curiosity and the install worked.

Powershell build error

```sh
error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

Again, from cmd, the install works perfectly fine.

It's worth noting that the keytar dependency requires Windows users to install python and VS 2015 (or `$ npm install --global --production windows-build-tools`), which kind of sucks. I'll open a PR to get that into the README.

**Comment by mamaso** [comment]
Does the file exist at the specified location? I expect that V110 doesn't exist.

You may need to set the `-msvs_version=<version>` when installing:
http://stackoverflow.com/questions/18774929/npm-install-g-karma-error-msb4019-the-imported-project-c-microsoft-cpp-defau

**Comment by fiveisprime** [comment]
I actually ended up adding the `VCTargetsPath` environment variable to my
`$PROFILE` to make this work.

`$env:VCTargetsPath='C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140'`
