### ISSUE TITLE
import/require not working on Azure functions

### ISSUE THREAD

**Issue by GeekOnGadgets** [serverless/serverless-azure-functions#67]
Hi,

So I am trying to do more than just `Hello Word` with serverless-azure-functions and running into problems. I have the following project structure.

```
-ProjectName
 -node_modules
 -src/
  -FileFolder
   --file1.js
  -SharedCodeFolder
   --sharedCode.js
 -.yml
 -package.json
```
So when i try to require/import into` file1.js` from` sharedCode.js` and try to run it on Azure it freaks out and keeps on saying  Error: Cannot find module` ../SharedCodeFolder/sharedCode`  and when i have all the code in one file everything is running fine. When i look at the generated folder `functions `(which i assume gets deployed to azure; does not have any shared code). Currently I am using serverless-webpack plugin. The code generated by severless-webpack plugin never gets picked by serverless-azure-function. Is there a way to point at the generated code ? 

 Can someone please help ? 

Thanks

**Comment by mamaso** [comment]
If you access `<projectname>.scm.azurewebsites.net/dev`, do you see the shared code folder?

**Comment by GeekOnGadgets** [comment]
Hi, 
Nope, just two files inside my function folder` function.json` and ` index.js`.

**Comment by pragnagopa** [comment]
We have an existing issue #34 tracking this.

**Comment by mamaso** [comment]
Closing as dupe of #34

**Comment by GeekOnGadgets** [comment]
As this is already work in progress. Will close this issue.
