### ISSUE TITLE
npm install on deploy

### ISSUE THREAD

**Issue by maticko** [serverless/serverless-azure-functions#69]
Uploading project `package.json` to Azure and then running `npm install` is not a good idea. It might be easy for quick start development, but should be avoided in any production-ready project. [NPM install is not immutable](https://ponyfoo.com/articles/immutable-npm-dependencies). So package we deployed to 'test' environment and the one we deployed to production environment might not be the same. 

This plugin should at least support a custom flag like `-no-install` or something similar that would prevent running `npm install` in Azure.

**Comment by lostintangent** [comment]
@maticko Thanks for the feedback! Definitely agreed that running `npm install` on separate environments could lead to subtle discrepancies between them, which is non-ideal.

That said, the deployed function would obviously need access to its dependencies, so I'd love to understand a little bit more about your proposal. If we added the `--no-install` flag to disable running `npm install` on Azure, would you expect that the `serverless deploy` command would zip the local `node_modules` folder and release that, along with the function code/metadata?

What about an NPM shrinkwrap file and/or Yarn lock files? Would it be helpful if those were respected as part of the deployment?

**Comment by maticko** [comment]
@lostintangent I looked into AWS implementation that already solved all these problems. What Azure implementation is missing is `package` step that executes before deployment (not during deployment). That should build the artifact that is then deployed in deploy step. Some build scripts can hook into that action and override it. The packaging step should consider `serverless.yml` package section that defines which files to include and which to exclude. 
So if a user forgets to add his `node_modules/` folder, then his app will fail to run after deploy. 
Have a look at [AWS Documentation](https://serverless.com/framework/docs/providers/aws/guide/packaging/). There is no need to invent this again. 

Is Azure Functions implementation constrained with a particular file structure that users must follow?

**Comment by jvanoostveen** [comment]
I was wondering wat the status was on this issue.
I'm encountering issues with the npm install on azure as well, as I'm working with private modules (well, simple not published to the public using some form of private/local/company npm registry). This fails the installation and makes serverless providing broken azure functions.
The `--no-install` does not seem to do anything. It still tries to install on Azure.

I played with ClaudiaJS as well, for stuff on AWS Lamda, and it will locally do an npm install --production and upload the result of that. Working with private npm registries then works out of the box.

**Comment by jvanoostveen** [comment]
Ow I misread on the `--no-install`, I assumed it was already in.
But it could do something like doing an npm install --production into some other directory and include those files to the artifact. At least then you don't need to mess with the include/excludes on a node_module level (to prevent micromanaging all your dependencies and their dependencies and their dependencies etc etc).

**Comment by mhenag** [comment]
The --no-install would be useful
I'm struggling to get the package include an exclude working with the plugin. It doesn't seem to obey it.
Have followed examples at [https://serverless.com/framework/docs/providers/azure/guide/packaging/](url)

```yaml
package:
    exlcude:
    - .gitignore
    - .git/**
    - node_modules/**
    - .someotherstuff
  include:
    - node_modules/a-private-one/**
    - functions/**
    - .npmrc
```

If it worked and you could control the uploaded package contents:
- include a .npmrc file to set save-exact=true so at least the different npm install runs will try to do the same thing. 
```bash
# .npmrc
save=true
save-exact=true
```

- Use the package include settings in serverless yaml to include node_modules/stuff_i_want
The npm install would have no affect for packages already present. 

- This could also allow including packages from private repos that we don't want to allow Azure access to.

Question:
The node environment is windows, so if the project has native dependencies wouldn't the deploy have to do npm install on the target environment anyway?

**Comment by celicoo** [comment]
What was the decision here? Is there a solution? I'm working with private repos and I'm having problem too in the deploy.
