### ISSUE TITLE
Add parameter 'sqlQuery' for Azure DocumentDB (direction: in)

### ISSUE THREAD

**Issue by brunonunes** [serverless/serverless-azure-functions#75]
x-azure-settings:
  sqlQuery: SELECT * FROM c WHERE c.id = 123
  ...

**Comment by pyryjook** [comment]
Yep, this would be very helpful!

**Comment by pyryjook** [comment]
https://github.com/serverless/serverless-azure-functions/blob/master/shared/bindings.json#L1347 DocumentId is set required, but it should be optional as should the `sqlQuery` too. But the `sqlQuery`is missing from the json.

**Comment by mhaggerty042** [comment]
Is there a workaround like a way to define the sqlQuery in code? I 'm trying to avoid logging into the console and adding it in the integration tab manually after each deploy.

**Comment by tbarlow12** [comment]
This looks like it was in reference to `v0`. Closing for now
