### ISSUE TITLE
*-function.json files aren't cleaned up post-packaging

### ISSUE THREAD

**Issue by lostintangent** [serverless/serverless-azure-functions#85]
The `*-function.json` files (that are generated as part of the packaging process) are never cleaned up. Ideally, we wouldn't leave behind any assets that aren't actually part of the end-user's app code. I'd love to discuss whether we should remove these post-packaging, since the generated zip file would already include them.

// CC @Trane9991 for your thoughts

**Comment by Trane9991** [comment]
@lostintangent yeah, I thought cleaning this files is a good idea, I will send PR to fix it soon.

**Comment by justinmchase** [comment]
They should also build inside of the `.serverless` folder not right in the root directory.
