### ISSUE TITLE
Unable to install on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by mjbright** [serverless/serverless-azure-functions#88]
This is my first attempt at using serverless, and I chose to try it with Azure but I'm unable to install this plugin.

Steps performed are:

First to install recent node (v6.11.3) /npm (v3.10.10) from nodesource repo:

```
curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh 
sudo apt-get install nodejs
sudo apt-get update
sudo apt-get upgrade
node --version
```

Then to install serverless and serverless-azure-functions:
```
sudo npm install -g serverless
sudo npm install -g serverless-azure-functions
```
serverless installation goes fine.
serverless-azure-functions installation fails with following errors:

> npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> 
> > keytar@4.0.4 install /usr/lib/node_modules/serverless-azure-functions/node_modules/keytar
> > node-gyp rebuild
> 
> gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/mbr/.node-gyp/6.11.3"
> gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/serverless-azure-functions/node_modules/keytar/.node-gyp"
> /bin/sh: 1: pkg-config: not found
> gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
> gyp ERR! configure error 
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
> gyp ERR! System Linux 4.4.0-79-generic
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /usr/lib/node_modules/serverless-azure-functions/node_modules/keytar
> gyp ERR! node -v v6.11.3
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok 
> /usr/lib
> └── (empty)
> 
> npm ERR! Linux 4.4.0-79-generic
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "serverless-azure-functions"
> npm ERR! node v6.11.3
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> 
> npm ERR! keytar@4.0.4 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the keytar@4.0.4 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the keytar package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs keytar
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls keytar
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/mbr/npm-debug.log
> npm ERR! code 1

**Comment by zndrk94** [comment]
I saw errors with `node-gyp` when I was installing node packages which needing some native building, like `xml2json`  which needed `node-expat`. I took for granted that my new AWS box didn't have `g++` and `make`. If it's a new box like I think you're saying, that might be the issue.

```
sudo apt-get install make
sudo apt-get install g++
```

I think `node-gyp` is the visible side-effect of the native build going wrong.

**Comment by mhaggerty042** [comment]
I ran into the same problem. I think the root problem in your logs is `gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 127 while in binding.gyp. while trying to load binding.gyp`

Dean @deanobalino posted a solution on gitter
> I managed to fix this, needed to install libsecret-1 with sudo apt-get install libsecret-1-dev

I couldn't figure out how to link directly to the gitter convo.

**Comment by kahwooi** [comment]
This issue is not solve yet?

**Comment by JohnMilazzo** [comment]
Thank you, @mhaggerty042 and @deanobalino.   That fixed it for me as well.
