### ISSUE TITLE
Add "create-sp" feature

### ISSUE THREAD

**Issue by christopheranderson** [serverless/serverless-azure-functions#9]
Add create-sp feature, which would allow for interactive login to generate a service principal and use its credentials when running the plugin

**Comment by lostintangent** [comment]
Agreed, this would be really nice for the getting started experience.

**Comment by cmatskas** [comment]
@christopheranderson I think there may be an issue with the interactive approach, and this is the 'forgetting the credentials' part. Unless you store them somewhere for the user, which could be insecure with credentials stored in plain text. 

I like the idea of forcing users to deploy through an SP, but we need to provide them with instructions on how to set them up and how to use the account credentials in the context of Serverless. The current docs need some clarifications (i.e per session credentials etc)

**Comment by lostintangent** [comment]
I'm closing this now that the plugin supports an interactive login process, and will generate an SP automatically. I believe that resolves the intent of this issue, but please re-open if it doesn't. Thanks!
