### ISSUE TITLE
Support for azure java functions

### ISSUE THREAD

**Issue by mozinrat** [serverless/serverless-azure-functions#92]
For feature proposals:

Azure recently started supporting java as lambda functions, just wanted to check if there is work for the active support of that.
If there is already a ticket to track that progress, would be nice if I can get hold of that to follow on.

**Comment by petomosy** [comment]
Is there any news on this topic?

Microsoft just made Java support in Azure Functions 2.0 generally available: https://azure.microsoft.com/de-de/updates/azure-functions-java-support-ga

I would be so happy to use serverless framework for AWS Lambda and Azure Funcions written in Java as well.

**Comment by tbarlow12** [comment]
Closing this in favor of duplicate: #368
