### ISSUE TITLE
Get ETIMEOUT while call serverless deploy

### ISSUE THREAD

**Issue by qs-wang** [serverless/serverless-azure-functions#97]
This is actually from the function isExistingFunctionApp with a non-existing function app.While running under my office network env, the dns.resolve4 returns ENOTFOUND, which is expected. However while running under my home network env, it returned ETIMEOUT, which failed the whole deploy process.
I'm not sure what's wrong there, but I think there should be a more reliable way to check the existence of function app?

**Comment by rupakg** [comment]
@qs-wang A little more context to the issue you are facing would be helpful.

**Comment by JohnReeson** [comment]
Same thing happened when I use a network with VPN. You can check if there's proxy in your home network.
