### ISSUE TITLE
Deployment arm template should set client affinity to off/disabled

### ISSUE THREAD

**Issue by fabiocav** [serverless/serverless-azure-functions#98]
The deployment ARM templates should set the client affinity enabled property to `false`

``` json
"clientAffinityEnabled": false
```

**Comment by pragnagopa** [comment]
Both the [Arm Templates](https://github.com/serverless/serverless-azure-functions/tree/b248b5bb514ad5e96d94204c957772171122a0b4/provider/armTemplates) need to be updated.

**Comment by eubruno** [comment]
Pull request #99

**Comment by lostintangent** [comment]
Resolved via #99
